queue: "Hosted VS2017"
variables:
  BuildConfiguration: Release

steps:
  - task: DotNetCoreCLI@2
    name: Build
    inputs:
      command: build
      projects: "*.sln"
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    name: Test
    inputs:
      command: test
      projects: "**/*Test*/*.csproj"
      arguments: "--configuration $(BuildConfiguration)"
      publishTestResults: true

  - task: DotNetCoreCLI@2
    name: Publish
    inputs:
      command: publish
      arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    name: Artifacts
    inputs:
      PathToPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactType: Container
      ArtifactName: "drop"

  - task: AzureRmWebAppDeployment@3
    name: Deploy
    inputs:
      ConnectedServiceName: "Jamiec Test Account ARM"
      WebAppName: "dotnetcore-yaml"
      Package: "$(Build.ArtifactStagingDirectory)/**/*.zip"
